server:
  port: 8084

spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/cpsdbms
    # username: root
    # password: admin@123
    url: jdbc:mysql://mysqldb:3306/cpsdbms
    username: sa
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: gateway-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka
      # defaultZone: http://localhost:8761/eureka


